https://gwrc.atlassian.net/browse/TEAMU-929 : Daily Aggregated Observations Multiple values for same day
Greater-Wellington-Regional-Council/Environmental-Outcomes-Platform pull request #235
Opened 2024-02-07 02:16 UTC by swapnasam

The .sql file will essentially remove daily duplicates from the core table.

Acceptance criteria
- View should not need the measurement_name column 
- Add the site name to the view, rather than site id
- Must only be one observation per site, per day

2024-02-13 00:27 UTC, smozely requested changes
I know we are talking later, but just first comments about keeping formatting consistent

2024-02-13 00:27 UTC, smozely commented on packages/Manager/src/main/resources/db/migration/V0040__observed_water_use_aggregated_daily.sql
> +PreviousMeasurement AS (
This, and others ... keep the naming consistent i.e. `snake_case` which is fairly standard for Postgres.

2024-02-13 00:27 UTC, smozely commented on packages/Manager/src/main/resources/db/migration/V0040__observed_water_use_aggregated_daily.sql
> +NonDuplicateMeasurements AS (
as above

2024-02-13 00:27 UTC, smozely commented on packages/Manager/src/main/resources/db/migration/V0040__observed_water_use_aggregated_daily.sql
> +FilledMeasurements AS (
As above

2024-02-13 00:55 UTC, swapnasam commented on packages/Manager/src/main/resources/db/migration/V0040__observed_water_use_aggregated_daily.sql
> +NonDuplicateMeasurements AS (
I have now changed. Thanks

2024-02-15 19:05 UTC, smozely approved these changes

2024-02-19 21:25 UTC, merged